import { Track } from "./types";

export const tracks: Track[] = [
  { id: 1, name: "The Goliath", length: 33.9 },
  { id: 2, name: "The Colossus", length: 34.3 },
  { id: 3, name: "Los Jardines Circuit", length: 1.6 },
  { id: 4, name: "Chihuahua Circuit", length: 1.5 },
  { id: 5, name: "Tierra Próspera Circuit", length: 2.1 },
  { id: 6, name: "Playa Azul Circuit", length: 2.5 },
  { id: 7, name: "Lookout Circuit", length: 1.6 },
  { id: 8, name: "Horizon Mexico Circuit", length: 2.0 },
  { id: 9, name: "Emerald Circuit", length: 1.6 },
  { id: 10, name: "Dunas Blancas Circuit", length: 5.3 },
  { id: 11, name: "Descansar Dorado Sprint", length: 3.9},
  { id: 12, name: "Estadio Circuit", length: 2 },
  { id: 13, name: "Cathedral Circuit", length: 1.4 },
  { id: 14, name: "Reservorio Sprint", length: 4.3 },
  { id: 15, name: "Copper Canyon Sprint", length: 5.9 },
  { id: 16, name: "Volcán Sprint", length: 5 },
  { id: 17, name: "Gran Pantano Sprint", length: 5.9 },
  { id: 18, name: "Sierra Verde Sprint", length: 4.7 },
  { id: 19, name: "Plaza Circuit", length: 2.2 },
  { id: 20, name: "Llanuras Sprint", length: 4.9 },
  { id: 21, name: "Panorámica Sprint", length: 3.7 },
  { id: 22, name: "Rivera Sprint", length: 6.1 },
  { id: 23, name: "Bola Ocho Circuit", length: 1.2 },
  { id: 24, name: "Bahía de Plano Circuit", length: 1.6 },
  { id: 25, name: "Arch of Mulegé Circuit", length: 1.8 },
  { id: 26, name: "Horizon Oval Circuit", length: 0.7 },
  { id: 27, name: "Vista del Mar Sprint", length: 4.2 },
  { id: 28, name: "Marigold Sprint", length: 3.9 },
  { id: 29, name: "Aeródromo Sprint", length: 3.9 },
  { id: 30, name: "Línea Costera Sprint", length: 5},
  { id: 31, name: "Winter Wonderland Circuit", length: 1.2},
  { id: 32, name: "Cloverleaf Sprint", length: 3.1},
  { id: 33, name: "San Juan Sprint", length: 3.3},
  { id: 34, name: "Valle del Río Sprint", length: 4.5},
  { id: 35, name: "Rocosa Sprint", length: 3.6},
  { id: 36, name: "Horizon Stadium Circuit", length: 1},
]
