import type { Track } from "../types";

export const tracks: Track[] = [
  { id: 1, name: "The Goliath", length: 33.9, type: "circuit" },
  { id: 2, name: "The Colossus", length: 34.3, type: "sprint" },
  { id: 3, name: "Los Jardines Circuit", length: 1.6, type: "circuit" },
  { id: 4, name: "Chihuahua Circuit", length: 1.5, type: "circuit" },
  { id: 5, name: "Tierra Próspera Circuit", length: 2.1, type: "circuit" },
  { id: 6, name: "Playa Azul Circuit", length: 2.5, type: "circuit" },
  { id: 7, name: "Lookout Circuit", length: 1.6, type: "circuit" },
  { id: 8, name: "Horizon Mexico Circuit", length: 2.0, type: "circuit" },
  { id: 9, name: "Emerald Circuit", length: 1.6, type: "circuit" },
  { id: 10, name: "Dunas Blancas Circuit", length: 5.3, type: "circuit" },
  { id: 11, name: "Descansar Dorado Sprint", length: 3.9, type: "sprint" },
  { id: 12, name: "Estadio Circuit", length: 2.0, type: "circuit" },
  { id: 13, name: "Cathedral Circuit", length: 1.4, type: "circuit" },
  { id: 14, name: "Reservorio Sprint", length: 4.3, type: "sprint" },
  { id: 15, name: "Copper Canyon Sprint", length: 5.9, type: "sprint" },
  { id: 16, name: "Volcán Sprint", length: 5.0, type: "sprint" },
  { id: 17, name: "Gran Pantano Sprint", length: 5.9, type: "sprint" },
  { id: 18, name: "Sierra Verde Sprint", length: 4.7, type: "sprint" },
  { id: 19, name: "Plaza Circuit", length: 2.2, type: "circuit" },
  { id: 20, name: "Llanuras Sprint", length: 4.9, type: "sprint" },
  { id: 21, name: "Panorámica Sprint", length: 3.7, type: "sprint" },
  { id: 22, name: "Rivera Sprint", length: 6.1, type: "sprint" },
  { id: 23, name: "Bola Ocho Circuit", length: 1.2, type: "circuit" },
  { id: 24, name: "Bahía de Plano Circuit", length: 1.6, type: "circuit" },
  { id: 25, name: "Arch of Mulegé Circuit", length: 1.8, type: "circuit" },
  { id: 26, name: "Horizon Oval Circuit", length: 0.7, type: "circuit" },
  { id: 27, name: "Vista del Mar Sprint", length: 4.2, type: "sprint" },
  { id: 28, name: "Marigold Sprint", length: 3.9, type: "sprint" },
  { id: 29, name: "Aeródromo Sprint", length: 3.9, type: "sprint" },
  { id: 30, name: "Línea Costera Sprint", length: 5.0, type: "sprint" },
  { id: 31, name: "Winter Wonderland Circuit", length: 1.2, type: "circuit" },
  { id: 32, name: "Cloverleaf Sprint", length: 3.1, type: "sprint" },
  { id: 33, name: "San Juan Sprint", length: 3.3, type: "sprint" },
  { id: 34, name: "Valle del Río Sprint", length: 4.5, type: "sprint" },
  { id: 35, name: "Rocosa Sprint", length: 3.6, type: "sprint" },
  { id: 36, name: "Horizon Stadium Circuit", length: 1.0, type: "circuit" },
];

